# Day 36 – Logging, Monitoring & SIEM

## Objective

Understand how organizations collect, monitor, analyze, and respond to security events using logs and Security Information and Event Management (SIEM) solutions.

---

# What is Logging?

Logging is the process of recording activities that occur on a system, application, or network.

Logs provide a history of events and help security teams investigate incidents.

Examples of logged activities:

- User logins
- Failed login attempts
- File access
- Software installation
- Configuration changes
- Network connections

Without logs, it is difficult to know what happened during a security incident.

---

# Why Logging is Important

Logs help organizations:

- Detect cyberattacks
- Investigate incidents
- Monitor user activity
- Meet compliance requirements
- Troubleshoot system problems

Logs are valuable evidence during digital forensic investigations.

---

# Types of Logs

## System Logs

Record operating system events.

Examples:

- System startup
- Driver errors
- Hardware failures

---

## Security Logs

Record security-related events.

Examples:

- Successful logins
- Failed logins
- Account lockouts
- Privilege changes

---

## Application Logs

Generated by applications.

Examples:

- Web server logs
- Database logs
- Email server logs

---

## Network Logs

Record network activity.

Examples:

- Firewall logs
- Router logs
- IDS/IPS logs
- VPN logs

---

# What is Monitoring?

Monitoring is the continuous observation of systems and networks to detect suspicious activity.

Security teams monitor for:

- Unauthorized logins
- Malware activity
- Network attacks
- Unusual user behavior
- System failures

Monitoring allows organizations to detect attacks quickly.

---

# What is SIEM?

SIEM stands for:

Security Information and Event Management.

A SIEM collects, centralizes, analyzes, and correlates logs from multiple devices and applications.

Instead of checking logs one by one, analysts use a SIEM to view everything in one place.

Examples:

- Microsoft Sentinel
- Splunk
- IBM QRadar
- Elastic Security

---

# How SIEM Works

Step 1:

Collect logs from:

- Servers
- Firewalls
- Routers
- Endpoints
- Applications
- Cloud services

↓

Step 2:

Normalize the data into a common format.

↓

Step 3:

Correlate related events.

↓

Step 4:

Generate alerts for suspicious activity.

↓

Step 5:

Security analysts investigate the alerts.

---

# Event Correlation

Event Correlation links multiple related events together to identify potential attacks.

Example:

One failed login is normal.

500 failed logins from different countries followed by one successful login is suspicious.

A SIEM recognizes this pattern and generates an alert.

---

# Alerting

SIEM systems generate alerts when suspicious activity matches predefined rules.

Examples:

- Multiple failed login attempts
- Malware detected
- Administrator account created
- Privilege escalation
- Large data transfer

Not every alert represents a real attack.

Analysts must investigate before taking action.

---

# False Positives

A False Positive occurs when a legitimate activity is mistakenly identified as malicious.

Example:

An employee mistypes their password several times while logging in.

The SIEM generates a brute-force alert.

No attack actually occurred.

---

# False Negatives

A False Negative occurs when malicious activity is not detected.

This is dangerous because attackers remain unnoticed.

Organizations constantly improve detection rules to reduce false negatives.

---

# Dashboard

SIEM dashboards display:

- Active alerts
- Threat trends
- Login activity
- Malware detections
- Network events

Dashboards help analysts quickly understand the organization's security posture.

---

# Why SIEM Matters

Without SIEM:

- Logs are scattered across many systems.
- Investigations take longer.
- Threats are harder to detect.

SIEM improves visibility and enables faster incident detection and response.

---

# Key Takeaways

- Logs record system activities.
- Monitoring continuously watches systems for suspicious behavior.
- SIEM centralizes and analyzes logs.
- Event Correlation connects related events.
- Alerts notify analysts of suspicious activity.
- False Positives are harmless events flagged as attacks.
- False Negatives are real attacks that go undetected.
